//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Second
{
    using System;
    using System.Collections.Generic;
    
    public partial class amigos
    {
        public int Id { get; set; }
        public int aceite { get; set; }
    
        public virtual UsuarioSet UsuarioSet { get; set; }
        public virtual UsuarioSet Convidados { get; set; }
    }
}
