//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Second
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class modelo_second : DbContext
    {
        public modelo_second()
            : base("name=modelo_second")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PerfilSet> PerfilSet { get; set; }
        public virtual DbSet<UsuarioSet> UsuarioSet { get; set; }
        public virtual DbSet<resultados_usuario> resultados_usuarioSet { get; set; }
        public virtual DbSet<amigos> amigosSet { get; set; }
    }
}
