//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Second
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioSet()
        {
            this.amigos_adicionados = new HashSet<amigos>();
            this.meus_convites = new HashSet<amigos>();
        }
    
        public long Id { get; set; }
        public string nick { get; set; }
        public string uuid { get; set; }
        public int Perfil_Id { get; set; }
    
        public virtual PerfilSet PerfilSet { get; set; }
        public virtual resultados_usuario resultados_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amigos> amigos_adicionados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amigos> meus_convites { get; set; }
    }
}
