//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Second
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioSet
    {
        public int Id { get; set; }
        public string nick { get; set; }
        public string uuid { get; set; }
        public int Perfil_Id { get; set; }
    
        public virtual PerfilSet PerfilSet { get; set; }
    }
}
